# Generated by Django 5.1.2 on 2024-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('tags', models.CharField(choices=[('Array', 'Array'), ('String', 'String'), ('Dynamic Programming', 'Dynamic Programming'), ('Tree', 'Tree'), ('Graph', 'Graph'), ('Backtracking', 'Backtracking'), ('Linked List', 'Linked List'), ('Binary Search', 'Binary Search')], max_length=255)),
                ('time_limit', models.IntegerField(help_text='Time limit in milliseconds')),
                ('memory_limit', models.IntegerField(help_text='Memory limit in kilobytes')),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('constraints', models.TextField()),
                ('sample_test_cases', models.JSONField(help_text="Provide sample test cases in JSON format (e.g., [{'input': '[2,7,11,15], 9', 'output': '[0,1]'}]).")),
                ('hidden_test_cases', models.JSONField(help_text="Provide hidden test cases in JSON format for evaluation (e.g., [{'input': '[1,5,3,7,11], 16', 'output': '[3,4]'}]).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LeetCodeQuestion',
        ),
    ]
