# Generated by Django 5.1.2 on 2024-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('useremail', models.EmailField(max_length=100, unique=True)),
                ('userpassword', models.CharField(max_length=100)),
                ('easy', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
                ('total_solved', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
